/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ContactForm_2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactForm_2.class.getName());

    private boolean bOnlyReqFields = false;
    
    private JLabel lblHint;
    
    private DefaultComboBoxModel<String> countries;
    
    public ContactForm_2() {
        initComponents();
        setLocationRelativeTo(null);
        cmbCountry.removeAllItems();
        String[] arrCountries = {"България","Германия","Франция","Канада"};
      //  for(String c : arrcountries){
        //    cmbCountry.addItem(c);
       //}
          lblHint = new JLabel("Задължителни: име, фамилия, град");
             pnlButtons.add(lblHint);
             
         countries = new DefaultComboBoxModel();
         cmbCountry.setModel(countries);
         for(String c : arrCountries){
             countries.addElement(c);
        }
    }
    
       private void clearFields(){
         txtFirstName.setText("");
         txtLastName.setText("");
         txtCity.setText("");
         cmbCountry.setSelectedItem(0);
         txtEmail.setText("");
         lbStatus.setText("gotovo");
    }
    
    /**
     * Creates new form ContactForm_2
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContact = new javax.swing.JPanel();
        pnlFields = new javax.swing.JPanel();
        lbFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lbCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lbCountry = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox<>();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pnlButtons = new javax.swing.JPanel();
        btnSample = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuContacts = new javax.swing.JMenu();
        miSplitName = new javax.swing.JMenuItem();
        miCountries = new javax.swing.JMenuItem();
        miRemoveCountry = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        miToggleFields = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContact.setLayout(new java.awt.BorderLayout());

        pnlFields.setPreferredSize(new java.awt.Dimension(150, 134));
        pnlFields.setLayout(new java.awt.GridLayout(5, 2, 6, 6));

        lbFirstName.setText("име");
        pnlFields.add(lbFirstName);
        pnlFields.add(txtFirstName);

        lbLastName.setText("фамилия");
        pnlFields.add(lbLastName);

        txtLastName.addActionListener(this::txtLastNameActionPerformed);
        pnlFields.add(txtLastName);

        lbCity.setText("град");
        pnlFields.add(lbCity);
        pnlFields.add(txtCity);

        lbCountry.setText("държава");
        pnlFields.add(lbCountry);

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlFields.add(cmbCountry);

        lbEmail.setText("имейл");
        pnlFields.add(lbEmail);
        pnlFields.add(txtEmail);

        pnlContact.add(pnlFields, java.awt.BorderLayout.PAGE_START);

        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnSample.setText("примерен");
        btnSample.addActionListener(this::btnSampleActionPerformed);
        pnlButtons.add(btnSample);

        btnClear.setText("изчисти");
        btnClear.addActionListener(this::btnClearActionPerformed);
        pnlButtons.add(btnClear);

        pnlContact.add(pnlButtons, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlContact, java.awt.BorderLayout.CENTER);

        lbStatus.setText("готово");
        getContentPane().add(lbStatus, java.awt.BorderLayout.SOUTH);

        mnuContacts.setText("Контакти");

        miSplitName.setText("разделяне");
        miSplitName.addActionListener(this::miSplitNameActionPerformed);
        mnuContacts.add(miSplitName);

        miCountries.setText("Държави");
        miCountries.addActionListener(this::miCountriesActionPerformed);
        mnuContacts.add(miCountries);

        miRemoveCountry.setText("изтриване");
        miRemoveCountry.addActionListener(this::miRemoveCountryActionPerformed);
        mnuContacts.add(miRemoveCountry);

        jMenuBar1.add(mnuContacts);

        mnuView.setText("изглед");

        miToggleFields.setText("задължителни");
        miToggleFields.addActionListener(this::miToggleFieldsActionPerformed);
        mnuView.add(miToggleFields);

        jMenuBar1.add(mnuView);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSplitNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSplitNameActionPerformed
        String name = txtFirstName.getText();
        try {
            String[] names = name.split(" ");
            //[0]->Ivan , [1]->Ivanov
            txtFirstName.setText(names[0]);
            txtLastName.setText(names[1]);
        } catch (Exception e) {
            lbStatus.setText("Въведете две имена през интервал");
        }
            
        
    }//GEN-LAST:event_miSplitNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSampleActionPerformed
     txtFirstName.setText("Stanimir");
     txtLastName.setText("Lozanov");
     cmbCountry.setSelectedItem("Bulgaria");
     txtEmail.setText("127950@students-ue.varna.bg");
     txtCity.setText("varna");
     
    }//GEN-LAST:event_btnSampleActionPerformed

    private void miToggleFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miToggleFieldsActionPerformed
         if(bOnlyReqFields == false){
               lbCountry.setVisible(false);
            lbEmail.setVisible(false);
             cmbCountry.setVisible(false);
            txtEmail.setVisible(false);
            miToggleFields.setText("Покажи незадължителните полета");
            bOnlyReqFields = true;
         }
            else {
              lbCountry.setVisible(true);
               cmbCountry.setVisible(true);
            lbEmail.setVisible(true);
            txtEmail.setVisible(true);
            miToggleFields.setText("Покажи само задължителните полета");
            bOnlyReqFields = false;
           
    }
    }//GEN-LAST:event_miToggleFieldsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void miCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCountriesActionPerformed
            String all =  "";
            for(int i = 0 ; i <countries.getSize(); i++){
                if(i !=0)
                    all+= " ,";
                all += countries.getElementAt(i);
            }
            lbStatus.setText("Durjavi (" + countries.getSize()+"):" + all);
    }//GEN-LAST:event_miCountriesActionPerformed

    private void miRemoveCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoveCountryActionPerformed
       countries.removeElement(cmbCountry.getSelectedItem());
    }//GEN-LAST:event_miRemoveCountryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactForm_2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSample;
    private javax.swing.JComboBox<String> cmbCountry;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JMenuItem miCountries;
    private javax.swing.JMenuItem miRemoveCountry;
    private javax.swing.JMenuItem miSplitName;
    private javax.swing.JMenuItem miToggleFields;
    private javax.swing.JMenu mnuContacts;
    private javax.swing.JMenu mnuView;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlContact;
    private javax.swing.JPanel pnlFields;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
